version: "3"

services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#    - "8080:8080"
#    depends_on:
#      - db
  db:
    image: mysql:8.0.21
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: 'desistdb'
      MYSQL_USER: 'desistdb'
      MYSQL_PASSWORD: 'desistdb'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
    cap_add:
      - SYS_NICE
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
